using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
namespace projectEuler.EvenFibonacciNumbers
{
    class EvenFibonacciNumbers
    {

        public static void Main(string[] args)
        {
            Console.WriteLine(fib());
            Console.ReadLine();
        }

        public static int fib()
        {
            int sum = 0;
            int a = 0;
            int b = 1;

            while (true)
            {
                int c = a + b;
                if (c > 4000000)
                    return sum;
                if (c % 2 == 0)
                    sum += c;
                a = b;
                b = c;
            }

        }
    }
}